/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

/**
 *
 * @author Usuario
 */
public class CreacionCuentaInfoForm extends javax.swing.JFrame {

    /**
     * Creates new form CreacionCuentaInfoForm
     */
    public CreacionCuentaInfoForm() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void inicarSistema(){
        alterarBotonSiguiente();
    }
    
    private void alterarBotonSiguiente(){
        if (this.SiguienteButton1.isEnabled()) {
            this.SiguienteButton1.setEnabled(false);
        }
        this.SiguienteButton1.setEnabled(true);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegistrarApellidoMajText1 = new javax.swing.JTextField();
        jSpinner4 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        RegistrarNombrejText1 = new javax.swing.JTextField();
        RegistrarDomiciliojText = new javax.swing.JTextField();
        RegistrarApellidoPajText1 = new javax.swing.JTextField();
        RegistrarApellidoMajText2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        SiguienteButton1 = new javax.swing.JButton();
        jSpinner3 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jSpinner5 = new javax.swing.JSpinner();
        jSpinner6 = new javax.swing.JSpinner();

        RegistrarApellidoMajText1.setBackground(new java.awt.Color(224, 224, 224));
        RegistrarApellidoMajText1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        RegistrarApellidoMajText1.setForeground(new java.awt.Color(196, 196, 196));
        RegistrarApellidoMajText1.setText("Segundo Apellido");
        RegistrarApellidoMajText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarApellidoMajText1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(87, 87, 86));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(108, 142, 132));
        jPanel2.setAutoscrolls(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 500));

        RegistrarNombrejText1.setBackground(new java.awt.Color(224, 224, 224));
        RegistrarNombrejText1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        RegistrarNombrejText1.setForeground(new java.awt.Color(196, 196, 196));
        RegistrarNombrejText1.setText("Nombre");
        RegistrarNombrejText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarNombrejText1ActionPerformed(evt);
            }
        });
        jPanel1.add(RegistrarNombrejText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 150, 30));

        RegistrarDomiciliojText.setBackground(new java.awt.Color(224, 224, 224));
        RegistrarDomiciliojText.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        RegistrarDomiciliojText.setForeground(new java.awt.Color(196, 196, 196));
        RegistrarDomiciliojText.setText("Domicilio");
        RegistrarDomiciliojText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarDomiciliojTextActionPerformed(evt);
            }
        });
        jPanel1.add(RegistrarDomiciliojText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 150, 30));

        RegistrarApellidoPajText1.setBackground(new java.awt.Color(224, 224, 224));
        RegistrarApellidoPajText1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        RegistrarApellidoPajText1.setForeground(new java.awt.Color(196, 196, 196));
        RegistrarApellidoPajText1.setText("Primer Apellido");
        RegistrarApellidoPajText1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarApellidoPajText1ActionPerformed(evt);
            }
        });
        jPanel1.add(RegistrarApellidoPajText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 150, 30));

        RegistrarApellidoMajText2.setBackground(new java.awt.Color(224, 224, 224));
        RegistrarApellidoMajText2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        RegistrarApellidoMajText2.setForeground(new java.awt.Color(196, 196, 196));
        RegistrarApellidoMajText2.setText("Segundo Apellido");
        RegistrarApellidoMajText2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarApellidoMajText2ActionPerformed(evt);
            }
        });
        jPanel1.add(RegistrarApellidoMajText2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 150, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(224, 224, 224));
        jLabel1.setText("Registrate");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 200, 100));

        SiguienteButton1.setBackground(new java.awt.Color(108, 142, 132));
        SiguienteButton1.setText("Siguiente");
        SiguienteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(SiguienteButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 100, 30));
        jPanel1.add(jSpinner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, 50, 20));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Fecha de Nacimiento");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));
        jPanel1.add(jSpinner5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 370, 50, 20));
        jPanel1.add(jSpinner6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 50, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarDomiciliojTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarDomiciliojTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrarDomiciliojTextActionPerformed

    private void RegistrarNombrejText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarNombrejText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrarNombrejText1ActionPerformed

    private void RegistrarApellidoPajText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarApellidoPajText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrarApellidoPajText1ActionPerformed

    private void RegistrarApellidoMajText1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarApellidoMajText1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrarApellidoMajText1ActionPerformed

    private void RegistrarApellidoMajText2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarApellidoMajText2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegistrarApellidoMajText2ActionPerformed

    private void SiguienteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SiguienteButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreacionCuentaInfoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreacionCuentaInfoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreacionCuentaInfoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreacionCuentaInfoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreacionCuentaInfoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField RegistrarApellidoMajText1;
    private javax.swing.JTextField RegistrarApellidoMajText2;
    private javax.swing.JTextField RegistrarApellidoPajText1;
    private javax.swing.JTextField RegistrarDomiciliojText;
    private javax.swing.JTextField RegistrarNombrejText1;
    private javax.swing.JButton SiguienteButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner3;
    private javax.swing.JSpinner jSpinner4;
    private javax.swing.JSpinner jSpinner5;
    private javax.swing.JSpinner jSpinner6;
    // End of variables declaration//GEN-END:variables
}
